server:
  name: gin-server
  port: 9000
log:
  log-path: E:/glog
  rotation-count: 8
consul:
  host: 127.0.0.1
  port: 8500
  token:
database:
  driver: mysql
  url: tcp(127.0.0.1:3306)/gindb?charset=utf8&parseTime=True&loc=Asia%2FShanghai
  username: root
  password: 123457

